stages:

  1.0_construct_edquality_mapper:
    cmd: python pipeline/1/1.0_construct_edquality_mapper.py
    params:
    - data.source
    deps:
    - data/edstats_pdb_quality.csv
    outs:
    - data/edquality_mapper_cache

  1.1_parse_sites_metadata:
    cmd: python pipeline/1/1.1_parse_sites_metadata.py
    params:
    - data.source
    - data.debug_max_files
    - data.remove_entities
    - data.skip_sites_with_entities 
    - data.backbone_treatment
    - data.metal_aggregation_distance
    - data.metal_site_radius
    - data.max_atoms_per_site
    - data.coordination_distance
    - data.min_coordinating_residues_per_site
    - data.min_residues_per_site
    - data.max_water_bfactor
    - data.n_cores
    deps:
    - pipeline/1/1.1_parse_sites_metadata.py
    - metalsitenn/dataloading.py
    - metalsitenn/placer_modules/cifutils.py
    - data/edquality_mapper_cache
    outs:
    - data/1/1.1_parse_sites_metadata

  2.0_get_stats:
    cmd: python pipeline/2_pretraining/2.0_get_stats.py
    params:
    - 2_pretraining.data.debug_max_sites
    - 2_pretraining.data.filtering
    - 2_pretraining.data.tokenization
    - 2_pretraining.data.dataloader_n_processes
    deps:
    - data/1/1.1_parse_sites_metadata
    outs:
    - data/2/2.0/element_counts.json
    metrics:
    - data/metrics/2/2.0/data_stats.json

  2.1_compute_node_class_weights:
    cmd: python pipeline/2_pretraining/2.1_compute_node_class_weights.py
    params:
    - 2_pretraining.data.tokenization.active_aggregators
    - 2_pretraining.data.loss_weighting.cel_count_to_weight_temperature
    - 2_pretraining.data.loss_weighting.cel_count_to_weight_clip_token
    deps:
    - data/2/2.0/element_counts.json
    outs:
    - data/2/2.1/node_class_weights.json
    plots:
    - data/plots/2/2.1/node_class_weights.png

  2.2_compute_null_model_loss:
    cmd: python pipeline/2_pretraining/2.2_null_model.py
    params:
    - 2_pretraining.data.debug_max_sites
    - 2_pretraining.data.filtering
    - 2_pretraining.data.splitting
    - 2_pretraining.data.tokenization
    - 2_pretraining.model.node_class_weights
    - 2_pretraining.model.node_class_label_smoothing
    deps:
    - data/1/1.1_parse_sites_metadata
    - data/2/2.0/element_counts.json
    - data/2/2.1/node_class_weights.json
    metrics:
    - data/metrics/2/2.2/null_model_metrics.json

  2.3_training:
    cmd: accelerate launch --config_file ${2_pretraining.accelerate_config} pipeline/2_pretraining/2.3_training.py
    params:
    - 2_pretraining.data.debug_max_sites
    - 2_pretraining.data.splitting
    - 2_pretraining.data.tokenization
    - 2_pretraining.model
    - 2_pretraining.accelerate_config
    - 2_pretraining.training
    deps:
    - data/1/1.1_parse_sites_metadata
    - data/2/2.1/node_class_weights.json
    # - metalsitenn/dataloading.py --- IGNORE code for now, wait until we have working full training script
    # - metalsitenn/nn
    # - metalsitenn/training/trainer.py
    outs:
    - data/2/2.3_pretraining/checkpoints
    - data/2/2.3_pretraining/final_model
    plots:
    - data/2/2.3_pretraining/dvclive/plots/metrics:
        x: step
    - data/2/2.3_pretraining/dvclive/plots/images/eval_confusion_matrix.png

  2.4_evaluate:
    cmd: python pipeline/2_pretraining/2.4_evaluate.py
    params:
    - 2_pretraining.data.debug_max_sites
    - 2_pretraining.data.splitting
    - 2_pretraining.data.tokenization
    - 2_pretraining.training
    deps:
    - data/1/1.1_parse_sites_metadata
    - data/2/2.3_pretraining/final_model
    metrics:
    - data/metrics/2/2.4/val_metrics.json
    - data/metrics/2/2.4/test_metrics.json


  2.5_extract_metal_embeddings:
    cmd: python pipeline/2_pretraining/2.5_extract_metal_embeddings.py --use-l1-norms --mask-metals
    params:
    - 2_pretraining.data.debug_max_sites
    - 2_pretraining.data.tokenization
    - 2_pretraining.training
    - 2_pretraining.tokenization
    deps:
    - data/1/1.1_parse_sites_metadata
    - data/2/2.3_pretraining/final_model
    outs:
    - data/2/2.5_embeddings/

    

