stages:
  1.1_parse_site_data:
    cmd: python pipeline/parse_site_data.py
    deps:
      - pipeline/1.1_parse_site_data.py
      - data/mf_sites
    outs:
      - data/site_labels.csv
    metrics:
      - data/metrics/site_label_metrics.json