stages:
  stage_name:
    cmd: python src/parse_site_data.py
    deps:
      - src/parse_site_data.py
      - data/mf_sites
    outs:
      - data/site_labels.csv
    metrics:
      - data/metrics/site_label_metrics.json