stages:

  1.0_construct_edquality_mapper:
    cmd: python pipeline/1/1.0_construct_edquality_mapper.py
    params:
    - data.source
    deps:
    - data/edstats_pdb_quality.csv
    outs:
    - data/edquality_mapper_cache

  1.1_parse_sites_metadata:
    cmd: python pipeline/1/1.1_parse_sites_metadata.py
    params:
    - data.source
    - data.debug_max_files
    - data.remove_entities
    - data.skip_sites_with_entities 
    - data.backbone_treatment
    - data.metal_aggregation_distance
    - data.metal_site_radius
    - data.max_atoms_per_site
    - data.coordination_distance
    - data.min_coordinating_residues_per_site
    - data.min_residues_per_site
    - data.max_water_bfactor
    - data.n_cores
    deps:
    - pipeline/1/1.1_parse_sites_metadata.py
    - metalsitenn/dataloading.py
    - metalsitenn/placer_modules/cifutils.py
    - data/edquality_mapper_cache
    outs:
    - data/1/1.1_parse_sites_metadata

  2.0_get_stats:
    cmd: python pipeline/2/2.0_get_stats.py
    params:
    - 2_pretraining.data.filtering
    - 2_pretraining.data.tokenization
    - 2_pretraining.data.dataloader_n_processes
    deps:
    - data/1/1.1_parse_sites_metadata
    outs:
    - data/2/2.0/element_counts.json
    metrics:
    - data/metrics/2/2.0/data_stats.json