data:
  # data source
  source: "/datasets/alphafold_data/data_v2/pdb_mmcif/mmcif_files" # Source of data, e.g. "mfs", "cif", "pdb"
  # source: "./tmp/tmp_cifs"
  debug_max_files: null # Maximum number of sites to use for debugging

  # parsing metal binding sites
  remove_entities: ['SO4', 'PO4', 'CL', 'BR', 'I', 'NO3', 'ACT', 'FMT', 'TRS', 'BIC', 'TRA', 'MES', 'BIS', 'EPE', 'IMD', 'GOL', 'ETG', 'PEG', 'PG4', 'PGE', 'MPD', 'DMS', 'SUC', 'TRE', 'XYL', 'ERY', 'ACE', 'EOH', 'MOH', 'IPA', 'BUT', 'DMF', 'DMSO', 'LDA', 'OP1', 'C8E', 'DDM', 'BOG', 'LMT', 'IOD', 'XE', 'KR', 'BCB', 'BTB', 'CR', 'MB', 'UNX', 'UNL', 'UNK', 'DUM', 'AMS', 'LIS', 'CAS', 'MPO', 'NEP', 'PEN', 'HEX']
  skip_sites_with_entities:  null # list of entitiy names or 'non_metal', in which case if a site contains an antity that does not have a metal, it is skipped (other than water)
  backbone_treatment: free # one of 'ca_only', 'free', 'bound'. For ca_only, Cb , O, N are removed. for free, just the bond is broken. For bound, the bond and all atoms are kept.
  metal_aggregation_distance: 4 # Distance in Angstroms to aggregate metals into a single site
  metal_site_radius: 6 # Radius in Angstroms from metal to include entities in metal binding site
  max_atoms_per_site: 400 # Maximum number of heavy atoms to consider in a system
  coordination_distance: 2.9 # Distance in Angstroms to consider an atom as coordinating a metal
  min_coordinating_residues_per_site: 3 # Minimum number of residues coordinating the metal to consider a site valid
  min_residues_per_site: 3 # Minimum number of residues in a site to consider it valid
  max_water_bfactor: 18
  n_cores: 104

2_pretraining:
  # related to data filtering and processing
  data:
    # filtering
    filtering:
      valid_metals: null
      min_metals: null
      max_metals: null
      min_organic_ligands: null
      max_organic_ligands: null
      min_waters: null
      max_waters: null
      min_nucleotides: null
      max_nucleotides: null
      min_amino_acids: 4
      max_amino_acids: null
      min_co_amino_acids: 2
      max_co_amino_acids: null
      min_sites_per_pdb: null
      max_sites_per_pdb: null
      max_unresolved_removed: 0
      max_resolution: 3.5
      max_max_rczd: null

    # tokenization
    tokenization:
      atom_features: ['element', 'charge', 'nhyd', 'hyb']
      bond_features: ['bond_order', 'is_in_ring', 'is_aromatic']
      active_aggregators: ['unknown_metal']


