data:
  # data source
  source: "/datasets/alphafold_data/data_v2/pdb_mmcif/mmcif_files" # Source of data, e.g. "mfs", "cif", "pdb"
  # source: "./tmp/tmp_cifs"
  debug_max_files: null # Maximum number of sites to use for debugging

  # parsing metal binding sites
  remove_entities: ['SO4', 'PO4', 'CL', 'BR', 'I', 'NO3', 'ACT', 'FMT', 'TRS', 'BIC', 'TRA', 'MES', 'BIS', 'EPE', 'IMD', 'GOL', 'ETG', 'PEG', 'PG4', 'PGE', 'MPD', 'DMS', 'SUC', 'TRE', 'XYL', 'ERY', 'ACE', 'EOH', 'MOH', 'IPA', 'BUT', 'DMF', 'DMSO', 'LDA', 'OP1', 'C8E', 'DDM', 'BOG', 'LMT', 'IOD', 'XE', 'KR', 'BCB', 'BTB', 'CR', 'MB', 'UNX', 'UNL', 'UNK', 'DUM', 'AMS', 'LIS', 'CAS', 'MPO', 'NEP', 'PEN', 'HEX']
  skip_sites_with_entities:  null # list of entitiy names or 'non_metal', in which case if a site contains an antity that does not have a metal, it is skipped (other than water)
  backbone_treatment: free # one of 'ca_only', 'free', 'bound'. For ca_only, Cb , O, N are removed. for free, just the bond is broken. For bound, the bond and all atoms are kept.
  metal_aggregation_distance: 4 # Distance in Angstroms to aggregate metals into a single site
  metal_site_radius: 6 # Radius in Angstroms from metal to include entities in metal binding site
  max_atoms_per_site: 400 # Maximum number of heavy atoms to consider in a system
  coordination_distance: 2.9 # Distance in Angstroms to consider an atom as coordinating a metal
  min_coordinating_residues_per_site: 3 # Minimum number of residues coordinating the metal to consider a site valid
  min_residues_per_site: 3 # Minimum number of residues in a site to consider it valid
  max_water_bfactor: 18
  n_cores: 104

2_pretraining:
  # related to data filtering and processing
  data:
    debug_max_sites: null
    # filtering
    filtering:
      valid_metals: null
      min_metals: null
      max_metals: null
      min_organic_ligands: null
      max_organic_ligands: null
      min_waters: null
      max_waters: null
      min_nucleotides: null
      max_nucleotides: null
      min_amino_acids: 4
      max_amino_acids: null
      min_co_amino_acids: 2
      max_co_amino_acids: null
      min_sites_per_pdb: null
      max_sites_per_pdb: null
      max_unresolved_removed: 0
      max_resolution: 3.5
      max_max_rczd: null

    # tokenization / collation
    tokenization:
      # should have 1:1 with MetalSiteCollator
      atom_features: ['element', 'charge', 'nhyd', 'hyb']
      bond_features: ['bond_order', 'is_in_ring', 'is_aromatic']
      k: 20 # graph size
      node_mlm_do: True
      node_mlm_rate: 0.15
      node_mlm_subrate_tweak: 0.0
      node_mlm_subrate_keep: 0.1

      # this is just here in case we want to train on slightly noised structures
      # its not expected that we will do full collapsing
      residue_collapse_do: False
      residue_collapse_rate: 0.0 # KEEP THIS AT 0.0, otherwise if the above is true, it will collapse whole residues
      residue_collapse_other_atom_noise_sigma: 0.1 # sigma of gaussian in angstroms to noise all atoms in system

      active_aggregators: ['unknown_metal']

    dataloader_n_processes: 8 # Number of processes to use for data loading

    loss_weighting:
      cel_count_to_weight_temperature: 2.0
      cel_count_to_weight_clip_token: '<METAL>' # clip upweighting of any rarer tokens than this by this weight

  model:
    cel_use_weights: True # Use class weights in cross-entropy loss

  training:
    # should have 1:1 with TrainingConfig
    max_epochs: 100
    eval_every: 50
    log_every: 10
    max_checkpoints: 5
    save_best_only: True

    lr_initial: 1e-4
    scheduler: "LambdaLR"
    lambda_type: "cosine"
    warmup_epochs: 0
    warmup_factor: 0.2
    lr_min_factor: 0.01
    decay_epochs: null
    decay_rate: 0.1
    
    # Optimization & Regularization  
    optimizer: "AdamW"
    batch_size: 32
    gradient_accumulation_steps: null
    weight_decay: 0.0
    clip_grad_norm: 1.0
    ema_decay: null
    
    # Infrastructure
    amp: False
    seed: null
    is_debug: False
    run_dir: null
    checkpoint_dir: null
    ddp: false
    
    # Evaluation
    primary_metric: "val_loss"
    
    # Early Stopping
    patience: null
    min_delta: 0.0
    
    # Training Resumption
    resume_from_checkpoint: null
    reset_optimizer: False
    
    # Data Loading & Sampling
    num_workers: 8
    pin_memory: True
    drop_last: True
    shuffle: True
    
    # Advanced Training
    run_val_at_start: True

    